### ISSUE TITLE
Create Answers Repo

### ISSUE THREAD

**Issue by mrkev** [cuappdev/clicker-backend#11]

**Comment by meganle** [comment]
What is the answer repo in charge of? Does it grab the correct responses or something? I can take a crack at it

**Comment by mrkev** [comment]
I'm thinking fetches the answers submitted for a given question (id).

**Comment by meganle** [comment]
Ok cause I believe the responses repo fetches all responses for a given question

**Comment by mrkev** [comment]
Ohhhhhhhh ok I'll look into that (some other day, I'm done for today lol)
