### ISSUE TITLE
Sessions Should Persist After Admin Leave

### ISSUE THREAD

**Issue by dantheli** [cuappdev/clicker-backend#75]
Sometimes clients disconnect from sockets due to network congestion or even inadvertently (e.g. iphone locks)

Right now this kills the entire session, but rather than let people lose their current sessions, perhaps sessions should be considered "Active" and we should allow admins to join their active sessions after disconnecting

**Comment by meganle** [comment]
d4bf7d6c0493832d8a6d31ecf229acc22a17e195
